
package ca.com.androidbinnersproject.auth;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;

import com.facebook.AccessToken;
import com.facebook.CallbackManager;
import com.facebook.FacebookCallback;
import com.facebook.FacebookException;
import com.facebook.FacebookSdk;
import com.facebook.GraphRequest;
import com.facebook.GraphResponse;
import com.facebook.HttpMethod;
import com.facebook.login.LoginManager;
import com.facebook.login.LoginResult;
import org.json.JSONException;
import org.json.JSONObject;
import java.util.Arrays;
import ca.com.androidbinnersproject.apis.AppLoginService;
import ca.com.androidbinnersproject.apis.BaseAPI;
import ca.com.androidbinnersproject.apis.FacebookLoginService;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import retrofit2.Retrofit;
import ca.com.androidbinnersproject.auth.keys.KeyManager;


public class FacebookAuth extends Authentication implements FacebookCallback<LoginResult>{

    private final CallbackManager facebookCallbackManager;
    private final LoginManager facebookLoginManager;
    private String LOG_TAG = getClass().getName();

    public FacebookAuth(Activity activity, OnAuthListener listener, KeyManager keyManager) {
        FacebookSdk.sdkInitialize(activity.getApplicationContext());

        this.activity = activity;
        facebookCallbackManager = CallbackManager.Factory.create();
        facebookLoginManager = LoginManager.getInstance();
        facebookLoginManager.registerCallback(facebookCallbackManager, this);

        //FacebookSdk.setApplicationId();
        //FacebookSdk.setClientToken();

		if(listener != null)
        	setOnAuthListener(listener);
    }

    @Override
    public void login() {
        facebookLoginManager.logInWithReadPermissions(activity,
                Arrays.asList("public_profile", "email"));
    }

    @Override
    public void logout() {
        facebookLoginManager.logOut();
    }

    @Override
    public void revoke() {
        AccessToken accessToken = AccessToken.getCurrentAccessToken();

        if(accessToken != null) {
            String user = accessToken.getUserId();

            //url to revoke login DELETE {user_id}/permissions
            String graphPath = user + "/permissions";

            final GraphRequest requestLogout = new GraphRequest(accessToken, graphPath, null, HttpMethod.DELETE, new GraphRequest.Callback() {
                @Override
                public void onCompleted(GraphResponse graphResponse) {
                    //call logout to clear token info and profile
                    logout();

                    onAuthListener.onRevoke();
                }
            });

            requestLogout.executeAsync();
        }else{
            onAuthListener.onLoginError("Token is null");
        }
    }

    @Override
    public void onSuccess(final LoginResult loginResult) {
        GraphRequest meRequest = GraphRequest.newMeRequest(loginResult.getAccessToken(), new GraphRequest.GraphJSONObjectCallback() {
            @Override
            public void onCompleted(JSONObject jsonObject, GraphResponse graphResponse) {
                String name = "";
                String email = "";
                String accessToken = loginResult.getAccessToken().getToken();

                try {
                    name = jsonObject.getString("name");
                    email = jsonObject.getString("email");
                } catch (JSONException e) {
                    Log.e(LOG_TAG, e.getMessage());
                }

                signInBackend(name, email, accessToken);
            }
        });

        Bundle params = new Bundle();
        params.putString("fields", "name, email, cover");

        meRequest.setParameters(params);
        meRequest.executeAsync();
    }

    /**
     * This method communicate with the backend server which is responsible to check
     * whether the Facebook Access Token is still valid, and if it is return a new JWT Token.
     *
     * @param name User Facebook's name
     * @param email User Facebook's email
     * @param accessToken Token generated by Facebook
     */
    private void signInBackend(final String name, final String email, String accessToken) {
        Retrofit retrofit = BaseAPI.getRetroInstance();
        FacebookLoginService service = retrofit.create(FacebookLoginService.class);

        Call<Profile> call = service.authenticate(accessToken);

        call.enqueue(new Callback<Profile>() {
            @Override
            public void onResponse(Response<Profile> response) {

                Profile profile = response.body();
                        profile.setName(name);
                        profile.setEmail(email);

                onAuthListener.onLoginSuccess(profile);
            }

            @Override
            public void onFailure(Throwable t) {
                onAuthListener.onLoginError("Error on trying to log on the backend.");
            }
        });
    }

    @Override
    public void onCancel() {
        onAuthListener.onLoginCancel();
    }

    @Override
    public void onError(FacebookException error) {
        Log.e(LOG_TAG, error.getMessage());
        onAuthListener.onLoginError(error.getMessage());
    }

    public CallbackManager getFacebookCallbackManager() {
        return facebookCallbackManager;
    }
}
